{{- if .Values.selfServiceIngress.enabled }}
{{- if eq .Values.selfServiceIngress.type "istio" }}
{{- if .Values.selfServiceIngress.istio.virtualservice.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "pbms.fullname" . }}-self-service
  labels:
    {{- include "pbms.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ default .Values.selfServiceHostname .Values.selfServiceIngress.istio.virtualservice.host | quote }}
  gateways:
  - {{ default (printf "%s-self-service" (include "pbms.fullname" .)) .Values.selfServiceIngress.istio.virtualservice.gateway }}
  http:
  - match:
    - uri:
        exact: /
    - uri:
        exact: /my
    - uri:
        prefix: /my/
    - uri:
        exact: /web
    - uri:
        exact: /web/login
    - uri:
        exact: /web/database/selector
    redirect:
      uri: /selfservice
  - match:
    - uri:
        prefix: /serviceprovider
    redirect:
      authority: {{ default .Values.serviceProviderHostname .Values.serviceProviderIngress.istio.virtualservice.host | quote }}
  - headers:
      request:
        set:
          x-forwarded-host: {{ default .Values.selfServiceHostname .Values.selfServiceIngress.istio.virtualservice.host | quote }}
          x-forwarded-proto: https
    match:
    - uri:
        prefix: {{ include "common.tplvalues.render" (dict "value" .Values.selfServiceIngress.istio.virtualservice.prefix "context" $) }}
    {{- if .Values.selfServiceIngress.istio.virtualservice.rewriteUri }}
    rewrite:
      uri: {{ include "common.tplvalues.render" (dict "value" .Values.selfServiceIngress.istio.virtualservice.rewriteUri "context" $) }}
    {{- end }}
    route:
    - destination:
        host: {{ tpl .Values.selfServiceIngress.istio.virtualservice.destination $ }}
        port:
          number: {{ tpl .Values.selfServiceIngress.istio.virtualservice.destinationPort $ }}
{{- end }}
{{- end }}
{{- end }}
