{{- if .Values.selfServiceIngress.enabled }}
{{- if eq .Values.selfServiceIngress.type "istio" }}
{{- if .Values.selfServiceIngress.istio.virtualservice.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "openg2p.fullname" . }}-self-service
  labels:
    {{- include "openg2p.labels" . | nindent 4 }}
spec:
  hosts:
  - {{ default .Values.global.selfServiceHostname .Values.selfServiceIngress.istio.virtualservice.host | quote }}
  gateways:
  - {{ default (printf "%s-self-service" (include "openg2p.fullname" .)) .Values.selfServiceIngress.istio.virtualservice.gateway }}
  http:
  - match:
    - uri:
        exact: /
    - uri:
        exact: /my
    - uri:
        prefix: /my/
    - uri:
        exact: /web
    - uri:
        exact: /web/login
    - uri:
        exact: /web/database/selector
    redirect:
      uri: /selfservice
  - match:
    - uri:
        prefix: /serviceprovider
    redirect:
      authority: {{ default .Values.global.serviceProviderHostname .Values.serviceProviderIngress.istio.virtualservice.host | quote }}
  - headers:
      request:
        set:
          x-forwarded-host: {{ default .Values.global.selfServiceHostname .Values.selfServiceIngress.istio.virtualservice.host | quote }}
          x-forwarded-proto: https
    route:
    - destination:
        host: {{ tpl .Values.selfServiceIngress.istio.virtualservice.destination $ }}
        port:
          number: {{ tpl .Values.selfServiceIngress.istio.virtualservice.destinationPort $ }}
{{- end }}
{{- end }}
{{- end }}
