{{- if .Values.selfserviceUi.enabled }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-ui
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.selfserviceUi.replicaCount }}
  {{- if .Values.selfserviceUi.updateStrategy }}
  strategy: {{- toYaml .Values.selfserviceUi.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" (dict "customLabels" .Values.selfserviceUi.podLabels "context" $) | nindent 6 }}
  template:
    metadata:
      {{- if .Values.selfserviceUi.podAnnotations }}
      annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.selfserviceUi.podAnnotations "context" $ ) | nindent 4 }}
      {{- end }}
      labels: {{- include "common.labels.standard" (dict "customLabels" .Values.selfserviceUi.podLabels "context" $) | nindent 8 }}
    spec:
      serviceAccountName: {{ include "pbms.beneficiary-portal.serviceAccountName" . }}
      {{- include "common.images.pullSecrets" (dict "images" (list .Values.image .Values.selfserviceUi.image) "global" .Values.global) -}}
      {{- if .Values.selfserviceUi.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.selfserviceUi.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.selfserviceUi.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.selfserviceUi.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.selfserviceUi.podAffinityPreset "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.selfserviceUi.podAntiAffinityPreset "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.selfserviceUi.nodeAffinityPreset.type "key" .Values.selfserviceUi.nodeAffinityPreset.key "values" .Values.selfserviceUi.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.selfserviceUi.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.selfserviceUi.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.selfserviceUi.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.selfserviceUi.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.selfserviceUi.priorityClassName }}
      priorityClassName: {{ .Values.selfserviceUi.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.selfserviceUi.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.selfserviceUi.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.selfserviceUi.initContainers }}
      initContainers:
        {{- include "common.tplvalues.render" (dict "value" .Values.selfserviceUi.initContainers "context" $) | nindent 8 }}
      {{- end }}
      containers:
        - name: pbms-beneficiary-portal-ui
          image: {{ include "common.images.image" (dict "imageRoot" .Values.selfserviceUi.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.selfserviceUi.image.pullPolicy }}
          {{- if .Values.selfserviceUi.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.selfserviceUi.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.selfserviceUi.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.selfserviceUi.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.selfserviceUi.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.selfserviceUi.command "context" $) }}
          {{- end }}
          {{- if .Values.selfserviceUi.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.selfserviceUi.args "context" $) }}
          {{- end }}
          env:
            {{- include "pbms.beneficiary-portal.ui.envVars" . | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.selfserviceUi.containerPort }}
          {{- if .Values.selfserviceUi.resources }}
          resources: {{- toYaml .Values.selfserviceUi.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.selfserviceUi.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.selfserviceUi.startupProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.selfserviceUi.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.selfserviceUi.livenessProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.selfserviceUi.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.selfserviceUi.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.selfserviceUi.extraVolumeMounts }}
          volumeMounts: {{- include "common.tplvalues.render" (dict "value" .Values.selfserviceUi.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.selfserviceUi.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.selfserviceUi.sidecars "context" $) | nindent 8 }}
        {{- end }}
      {{- if .Values.selfserviceUi.extraVolumes }}
      volumes: {{- include "common.tplvalues.render" (dict "value" .Values.selfserviceUi.extraVolumes "context" $) | nindent 8 }}
      {{- end }}
{{- end }}
